In [1]:
import pandas as pd
data=pd.read_csv("student_performance.csv")
data

     Student_ID         Name  Math_Score  Science_Score  English_Score
0             1    Student_1          58             51             57
1             2    Student_2          89             51             88
2             3    Student_3          81             55             60
3             4    Student_4          96             78             79
4             5    Student_5          40             73             75
..          ...          ...         ...            ...            ...
495         496  Student_496          44             73             98
496         497  Student_497          64             53             98
497         498  Student_498          72             90             91
498         499  Student_499          57             54             64
499         500  Student_500          89             81             50

[500 rows x 5 columns]

In [2]:
data.isnull().sum()

Student_ID       0
Name             0
Math_Score       0
Science_Score    0
English_Score    0
dtype: int64

In [4]:
data['Total_Score']=data['Math_Score']+data['Science_Score']+data['English_Score']

In [5]:
data

,Student_ID,Name,Math_Score,Science_Score,English_Score,Total_Score
0,1,Student_1,58,51,57,166
1,2,Student_2,89,51,88,228
2,3,Student_3,81,55,60,196
3,4,Student_4,96,78,79,253
4,5,Student_5,40,73,75,188
...,...,...,...,...,...,...
495,496,Student_496,44,73,98,215
496,497,Student_497,64,53,98,215
497,498,Student_498,72,90,91,253
498,499,Student_499,57,54,64,175
499,500,Student_500,89,81,50,220

In [12]:
data['Percentage']=(data['Total_Score']/3)
data

,Student_ID,Name,Math_Score,Science_Score,English_Score,Total_Score,Percentage
0,1,Student_1,58,51,57,166,55.333333
1,2,Student_2,89,51,88,228,76.000000
2,3,Student_3,81,55,60,196,65.333333
3,4,Student_4,96,78,79,253,84.333333
4,5,Student_5,40,73,75,188,62.666667
...,...,...,...,...,...,...,...
495,496,Student_496,44,73,98,215,71.666667
496,497,Student_497,64,53,98,215,71.666667
497,498,Student_498,72,90,91,253,84.333333
498,499,Student_499,57,54,64,175,58.333333
499,500,Student_500,89,81,50,220,73.333333

In [14]:
def grade_(Percentage):
    if Percentage > 90 :
        return 'A'
    elif Percentage <=90 and Percentage >80:
        return 'B'
    elif Percentage <=80 and Percentage >70:
        return 'C'
    elif Percentage <=70 and Percentage >36:
        return 'Pass'
    else:
        return 'F'
data['Grade']=data['Percentage'].apply(grade_)

In [15]:
data

,Student_ID,Name,Math_Score,Science_Score,English_Score,Total_Score,Percentage,Grade
0,1,Student_1,58,51,57,166,55.333333,Pass
1,2,Student_2,89,51,88,228,76.000000,C
2,3,Student_3,81,55,60,196,65.333333,Pass
3,4,Student_4,96,78,79,253,84.333333,B
4,5,Student_5,40,73,75,188,62.666667,Pass
...,...,...,...,...,...,...,...,...
495,496,Student_496,44,73,98,215,71.666667,C
496,497,Student_497,64,53,98,215,71.666667,C
497,498,Student_498,72,90,91,253,84.333333,B
498,499,Student_499,57,54,64,175,58.333333,Pass
499,500,Student_500,89,81,50,220,73.333333,C

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x=data.drop(['Grade','Name','Student_ID','Total_Score','Percentage'],axis=1)
y=data['Grade']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array(['Pass', 'Pass', 'Pass', 'C', 'Pass', 'Pass', 'A', 'Pass', 'C',
       'Pass', 'B', 'C', 'C', 'Pass', 'C', 'Pass', 'C', 'Pass', 'Pass',
       'B', 'C', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'B', 'B', 'Pass',
       'C', 'C', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'C',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'C', 'C', 'C', 'Pass',
       'Pass', 'Pass', 'C', 'Pass', 'C', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'C', 'B', 'Pass', 'B', 'Pass', 'C', 'Pass', 'C',
       'B', 'Pass', 'C', 'C', 'C', 'Pass', 'Pass', 'Pass', 'C', 'C', 'C',
       'Pass', 'C', 'Pass', 'Pass', 'B', 'Pass', 'C', 'Pass', 'B', 'A',
       'B', 'Pass', 'Pass', 'B', 'B', 'C', 'C', 'Pass', 'C', 'C', 'Pass',
       'C', 'C', 'C', 'Pass', 'C', 'Pass', 'C', 'C', 'C', 'Pass', 'C',
       'Pass', 'C', 'C', 'Pass', 'Pass', 'B', 'C', 'C', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'C'], dtype=object)

In [20]:
from sklearn.metrics import accuracy_score
print(model.score(x_train,y_train))
print(model.score(x_test,y_test))

print(accuracy_score(y_test,y_pred))

1.0
1.0
1.0